services:
  node:
    container_name: una-theme-kit
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
     - "4200:4200"
    stdin_open: true
    tty: true
    volumes:
      - ./workspace:/workspace
