name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main  # Triggers on push to main branch
  workflow_dispatch:  # Allows manual trigger from Actions tab

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './workspace/package-lock.json'

      - name: Install dependencies
        working-directory: ./workspace
        run: npm ci

      - name: Build Angular app for GitHub Pages
        working-directory: ./workspace
        run: npm run build -- --configuration=github-pages

      - name: Copy index.html to 404.html (for SPA routing)
        working-directory: ./workspace
        run: cp dist/una-theme-kit-demo-app/browser/index.html dist/una-theme-kit-demo-app/browser/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './workspace/dist/una-theme-kit-demo-app/browser'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
